channels:
- conda-forge
dependencies:
- python=3.8.16
- pip<=23.0.1
- pip:
  - mlflow
  - cloudpickle==2.2.0
  - datasets==2.3.2
  - openmim
  - torch==1.11.0
  - torchvision
  - transformers==4.25.1
  - albumentations==1.3.0
name: mlflow-env
